# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-06 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
        migrations.RemoveField(
            model_name='sales_form',
            name='date',
        ),
    ]
