# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-08 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20200106_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales_form',
            old_name='contact_details',
            new_name='contact',
        ),
        migrations.AlterField(
            model_name='sales_form',
            name='image',
            field=models.ImageField(upload_to='static/img'),
        ),
    ]
